trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - backend
      - cloud
      - .vscode

pool:
  name: Default
  vmImage: self-hosted

variables:
  - name: projectRoot
    value: '$(System.DefaultWorkingDirectory)/frontend'
  - name: buildPath
    value: '$(projectRoot)/dist'
  - group: vg-frontend

stages:
- stage: Build
  displayName: 'Build frontend'
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '20.x'
        checkLatest: true
    
    - script: |
        npm install
        npm run build --if-present
      displayName: 'npm install & build'
      workingDirectory: $(projectRoot)
      env:
        VITE_GRAPHQL_API_URL: $(VITE_GRAPHQL_API_URL)
        VITE_GRAPHQL_API_URL_WS: $(VITE_GRAPHQL_API_URL_WS)
        VITE_BACKEND_URL: $(VITE_BACKEND_URL)
        VITE_TRANSLATE_API_KEY: $(VITE_TRANSLATE_API_KEY)
        VITE_TRANSLATE_API_LOCATION: $(VITE_TRANSLATE_API_LOCATION)
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(buildPath)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Zip build'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'frontend'
        publishLocation: 'Container'
      displayName: 'Publish artifact'

- stage: Deploy
  displayName: 'Deploy frontend'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    environment: 'prod'
    displayName: 'Deploy frontend'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure for Students(a01e0481-f64f-4175-bb08-5fb645938877)'
              appType: 'webAppLinux'
              appName: 'webapp-musicboxd-746263'
              package: '$(Pipeline.Workspace)/frontend/$(Build.BuildId).zip'
              deploymentMethod: auto
              appSettings: -VITE_GRAPHQL_API_URL "$(VITE_GRAPHQL_API_URL)" -VITE_GRAPHQL_API_URL_WS "$VITE_GRAPHQL_API_URL_WS" -VITE_BACKEND_URL "$(VITE_BACKEND_URL)" -VITE_TRANSLATE_API_KEY "$(VITE_TRANSLATE_API_KEY)" -VITE_TRANSLATE_API_LOCATION "$(VITE_TRANSLATE_API_LOCATION)"
            displayName: 'Deploy to AzureWebApp'