// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type User struct {
	ID          *string `json:"_id,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	AvatarURL   *string `json:"avatar_url,omitempty"`
	SpotifyID   *string `json:"spotify_id,omitempty"`
	Email       *string `json:"email,omitempty"`
	Country     *string `json:"country,omitempty"`
}
